### ISSUE TITLE
Can I securely fetch templates without auth?

### ISSUE THREAD

**Issue by trych** [johannschopplich/kirby-headless-starter#1]
Hi Johann,

thanks a lot for the headless starter. After having started the whole Kirby headless discussion a few days agai, I am still trying to make sense of it.

Lukas told me in the Discord channel:
> Yes, absolutely. Content representations are intended to be used without authentication. As you can fully control the data that they output, you can make sure that no sensitive data is leaked.

> If you want to request the data from a JS frontend, the data is considered public by definition.

Can the templates in your headless starter used in the same sense? As in, *without* auth, only exposing the public data that I choose? Or will I expose sensitive information as soon as I turn of the token option?

Would love to set up the templates as you've shown in the README and then consume those via a JS frontend without auth. Is this possible and does this make sense?

Thanks!

**Comment by johannschopplich** [comment]
Hi there,

yes, you can use this kit without authentication, of course. Taken from the usage section: 

> ⚠️ Without a token your page content will be publicly accessible by everyone.

Thus, just leave the environment variable `KIRBY_HEADLESS_API_TOKEN` empty or delete it from your `.env` file. I've also update the README to make clear on how to use this headless kit tokenless.

With the template approach – which is pretty similar to content representations – you only expose data that you choose. 

You can then fetch your data without having to provide an authentication header, like:

```js
import { $fetch } from "ohmyfetch";

const response = await $fetch("<website-url>/about.json");

console.log(response);
```

Have fun!
