### ISSUE TITLE
PHP8 error ? "Automatic conversion of false to array is deprecated"

### ISSUE THREAD

**Issue by ebz8** [johannschopplich/kirby-headless-starter#4]
Hi Johann,

Thank you so much for this starter.

I explored it without modifying the configuration and when I create any draft (a note or a page), I have the following message: "Automatic conversion of false to array is deprecated". I can't edit or delete it until the status is "published".

Are you aware of this error? How could I fix it?

Thank you.

Elba

**Comment by johannschopplich** [comment]
Hi Elba, I can't reproduce your issue. Running PHP 8.2 on my machine. 

Could you please share your environment configuration? I won't be able to help otherwise.

**Comment by ebz8** [comment]
Hi Johann,
My bad... I reset " KIRBY_HEADLESS_FRONTEND_URL= " in .env and this error disappeared. It's still hard for me to understand Kirby from the "headless" angle. Thank you for your work, it's very helpful. Have a good day!

**Comment by johannschopplich** [comment]
I'm not sure if I follow. The `KIRBY_HEADLESS_FRONTEND_URL` env variable can be left empty. It should contain the URL to your frontend application, if applicable, and if editors should be able to see the preview button.

OK, good luck then, digging into the headless world of Kirby! 🙂
