### ISSUE TITLE
Deployment issues when moving files to FTP server

### ISSUE THREAD

**Issue by flornkm** [johannschopplich/kirby-headless-starter#5]
Hi @johannschopplich,
first of all, thanks for all the hard work on the headless plugin / startpack. I really appreciate that.

I'm relatively new to the Kirby CMS space and am building a first project with it right now. I have massive issues moving everything to the production server. I'm usually working in the JS space, so maybe I'm too used to having a dist folder which I can easily deploy on Vercel etc. but whatever.

The weird thing is, in development everything is running smoothly.

My setup is as following, I have a monorepo and a completely separated CMS which acts as headless backend from which I can fetch data from. The other folder of the repo is a (obviously also separated) frontend application with NextJS. No questions regarding the frontend, as mentioned above, everything works exactly as I want it to in development, however when moving the files from the CMS folder into the webspace via FTP the server can't find the page.

Here are some things that may cause this error:
- The "default" starter kit from kirby isn't using the public folder in which your `.htaccess` and `index.php` is located. The default starter kit from kirby works fine on the webserver btw.
- Something on the end of the webserver has to be changed (I don't have access to it as I'm building a project for friends)

I hope I could help you a bit understand my problem. If there's a quickfix for that you already know what I have to change, I would be insanely happy to hear from you as this is currently blocking further development.

Again, thanks for your great work and have a good evening!

**Comment by flornkm** [comment]
Closing this issue as I could resolve the problem. The problem was indeed the public folder, I put the index.php and the htaccess into the root and works perfectly. Thanks anyway! :)

**Comment by johannschopplich** [comment]
Glad to hear you have found the solution already!
